name: Build

on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy
    runs-on: windows-latest

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: HOLA
        run: echo Hello 
    
